.TH ELEKTROID "1" "Jan 2023"

.SH NAME
elektroid \- Sample and MIDI device manager (GUI)

.SH SYNOPSIS
.B elektroid
.RI [ options ]

.SH DESCRIPTION
.B elektroid
is part of Elektroid, a sample and MIDI device manager. See man elektroid-cli for the CLI application and the full list of features.

.SH OPTIONS
.TP
\fB\-l\fR, \fB--local-directory\fR <local directory>
open the provided local directory
.TP
\fB\-v\fR, \fB--verbose\fR
show verbose output. Use it more than once for more verbosity.
.TP
\fB\-h\fR, \fB--help\fR
show a little help about the options

.SH "AUTHOR"
elektroid was written by David García Goñi <dagargo@gmail.com>.

.PP
This manual page was written by Dennis Braun <snd@debian.org>
for the Debian project (but may be used by others).
