.TH ELEKTROID-CLI "1" "Feb 2020"
.SH NAME
elektroid-cli \- sample transfer CLI application for Elektron devices
.SH SYNOPSIS
.B elektroid-cli
.RI [ options ]
.RI command
.SH DESCRIPTION
.B elektroid-cli
provides the same funcionality than elektroid. See man elektroid for the GUI application.
.PP
Provided paths must always be prepended with the device id and a colon (':'), e.g. 0:/samples.
.SH COMMANDS
.TP
.B ld
List compatible devices
.TP
.B info [device number]
Show device info
.TP
.B ls [device number]:[path to directory]
List directory contents
.TP
.B mkdir [device number]:[path to directory]
Create a directory
.TP
.B rmdir [device number]:[path to directory]
Delete a directory. The directory must be empty.
.TP
.B upload [sample] [device number]:[path to directory or sample]
Upload a sample. If the path does not exist it will be created. The supported audio file formats are aiff, flac, ogg and wav.
.TP
.B download [device number]:[path to sample]
Download a sample. Samples will be stored locally as 16-bit, 48kHz wav files.
.TP
.B mv [device number]:[path to origin sample] [device number]:[path to destination directory or sample]
Move a sample. If the destination path does not exist it will be created.
.TP
.B rm [device number]:[path to sample]
Delete a sample
.SH OPTIONS
.TP
\fB\-v\fR
Show verbose output. Use it twice for more verbosity.
.PP
.SH "SEE ALSO"
The GitHub page provides some examples: <https://github.com/dagargo/elektroid>
.SH "AUTHOR"
elektroid-cli was written by David García Goñi <dagargo@gmail.com>.
.PP
This manual page was written by Dennis Braun <d_braun@kabelmail.de>
for the Debian project (but may be used by others).
