.TH ELEKTROID-CLI "1" "Feb 2020"
.SH NAME
elektroid-cli \- sample transfer cli application for Elektron devices
.SH SYNOPSIS
.B elektroid-cli
.RI [ options ]
.SH DESCRIPTION
Elektroid-cli provides the same funcionality than elektroid. See man elektroid for the GUI application.
.PP
Provided paths must always be prepended with the device id and a colon (':'), e.g. 0:/samples. Here are the available commands.
.SH OPTIONS
.TP
.B ld
List compatible devices
.TP
.B info [device number]
Show device info
.TP
.B ls [device number]:/
List directory contents
.TP
.B mkdir [device number]:/[directory]
Create a directory
.TP
.B rmdir [device number]:/[directory]
Delete a directory
.TP
.B upload [file] [device number]:/
Upload a file
.TP
.B dowload [device number]:/[file]
Download a file
.TP
.B mv [device number]:/[file0] [device number]:/[file1]
Move a file
.TP
.B rm [device number]:/[file]
Delete a file
.PP
.SH "SEE ALSO"
The github page provides some examples: <https://github.com/dagargo/elektroid>
.SH "AUTHOR"
elektroid-cli was written by David García Goñi <dagargo@gmail.com>.
.PP
This manual page was written by Dennis Braun <d_braun@kabelmail.de>
for the Debian project (but may be used by others).
