.TH ELEKTROID "1" "Feb 2020"
.SH NAME
elektroid \- sample transfer application for Elektron devices
.SH SYNOPSIS
.B elektroid
.RI [ options ]
.SH DESCRIPTION
.B Elektroid
is a GNU/Linux sample transfer application for Elektron devices. See man elektroid-cli for the CLI application.
.PP
With elektroid you can easily load audio files like flac or wav into your elektron sampler. You can also transfer audio samples from your elektroid device to your local hard disk.
.PP
Elektroid has been reported to work with Model:Samples, Digitakt and Analog Rytm mk1 and mk2.
.SH OPTIONS
.TP
\fB\-l\fR <local directory>
Open the provided local directory
.TP
\fB\-v\fR
Show verbose output. Use it twice for more verbosity.
.PP
.SH "AUTHOR"
elektroid was written by David García Goñi <dagargo@gmail.com>.
.PP
This manual page was written by Dennis Braun <d_braun@kabelmail.de>
for the Debian project (but may be used by others).
