.TH ELEKTROID-CLI "1" "Dec 2021"

.SH NAME
elektroid-cli \- transfer CLI application for Elektron devices

.SH SYNOPSIS
.B elektroid-cli
.RI [ options ]
.RI command

.SH DESCRIPTION
.B elektroid-cli
provides the same funcionality than elektroid. See man elektroid for the GUI application.
.PP
Provided paths must always be prepended with the device id and a colon (':'), e.g. 0:/samples. Paths pointing to a data, sound or project file use the index of a file instead of its name.

.SH DEVICE COMMANDS
.TP
[ \fBld\fR | \fBlist-devices\fR ]
List compatible devices
.TP
[ \fBdf\fR | \fBinfo-storage\fR ] device_number
Show size and use of +Drive and RAM where available
.TP
\fBinfo\fR device_number
Show device info
.TP
\fBupgrade\fR firmware device_number
Upgrade the device

.SH FILESYSTEM COMMANDS
.PP
Filesystem commands must be followed by a hyphen ('-') and a filesystem name. The available filesystemas are sample, sound, project, data, preset and raw. Data is an unpackaged form of sound and project and so is raw with regards to preset.
.TP
[ \fBls\fR | \fBlist\fR ] device_number:path_to_directory
List directory contents
.TP
\fBmkdir\fR device_number:path_to_directory
Create a directory and its parent directories as needed
.TP
[ \fBrmdir\fR | \fBrm\fR ] device_number:path_to_directory
Delete a directory recursively
.TP
[ \fBul\fR | \fBupload\fR ] file device_number:path_to_file_or_directory
Upload a file. If the path does not exist it will be created. For the sample filesystem, the supported audio file formats are aiff, flac, ogg and wav.
.TP
[ \fBdl\fR | \fBdownload\fR ] device_number:path_to_file_or_directory
Download a file into the current directory. For the sample filesystem, samples will be stored locally as 16-bit, 48kHz wav files.
.TP
\fBmv\fR device_number:path_to_file_or_directory device_number:path_to_file_or_directory
Move a file. If the destination path does not exist, it will be created.
.TP
\fBrm\fR device_number:path_to_file
Delete a file
.TP
\fBcl\fR device_number:path_to_file
Clear file
.TP
\fBcp\fR device_number:path_to_file device_number:path_to_file
Copy a file
.TP
\fBsw\fR device_number:path_to_file device_number:path_to_file
Swap files

.SH OPTIONS
.TP
\fB\-v\fR
Show verbose output. Use it more than once for more verbosity.
.PP

.SH EXAMPLES
.PP
Upload a sample.
.TP
\tul-sample square.wav 0:/waveforms
.PP
Download a preset into the current directory.
.TP
\tdl-raw 0:/snare/snare.mc-snd
.PP
List projects.
.TP
\tls-project 0:/

.SH "SEE ALSO"
The GitHub page provides some examples: <https://github.com/dagargo/elektroid>

.SH "AUTHOR"
elektroid-cli was written by David García Goñi <dagargo@gmail.com>.
.PP
This manual page was written by Dennis Braun <snd@debian.org>
for the Debian project (but may be used by others).
