.TH ELEKTROID "1" "Dec 2021"

.SH NAME
elektroid \- transfer application for Elektron devices

.SH SYNOPSIS
.B elektroid
.RI [ options ]

.SH DESCRIPTION
.B Elektroid
is a GNU/Linux transfer application for Elektron devices. See man elektroid-cli for the CLI application.
.PP
With Elektroid you can easily upload and download audio files, projects, sounds and presets to and from Elektron devices. It can also be used to send and receive MIDI SysEx files.
.PP
Elektroid has been reported to work with Model:Samples, Model:Cycles, Digitakt, Digitone and Analog Rytm MKI and MKII.

.SH OPTIONS
.TP
\fB\-l\fR, \fB--local-directory\fR <local directory>
Open the provided local directory
.TP
\fB\-v\fR, \fB--verbose\fR
Show verbose output. Use it more than once for more verbosity.
.TP
\fB\-h\fR, \fB--help\fR
Show a little help about the options
.PP

.SH "AUTHOR"
elektroid was written by David García Goñi <dagargo@gmail.com>.

.PP
This manual page was written by Dennis Braun <d_braun@kabelmail.de>
for the Debian project (but may be used by others).
