.TH ELEKTROID "1" "Feb 2020"
.SH NAME
elektroid \- sample transfer application for Elektron devices
.SH SYNOPSIS
.B elektroid
.RI [ options ]
.SH DESCRIPTION
Elektroid is a GNU/Linux sample transfer application for Elektron devices. This is the elektroid GUI application. See man elektroid-cli.1 for the CLI application.
.PP
Elektroid has been reported to work with Model:Samples, Digitakt and Analog Rytm mk1 and mk2.
.SH OPTIONS
.TP
\fB\-l\fR localdir
Open with localdir
.TP
\fB\-v\fR verbose
Show verbose output
.PP
.SH "AUTHOR"
elektroid was written by David García Goñi <dagargo@gmail.com>.
.PP
This manual page was written by Dennis Braun <d_braun@kabelmail.de>
for the Debian project (but may be used by others).
