title: Elektroid
author:
  name: David García Goñi
  email: "dagargo@gmail.com"
description: Sample and MIDI device manager
baseurl: "/elektroid/"
url: "https://dagargo.github.io/elektroid/"

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  hide_site_feed_link: true
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/dagargo"

header_pages:
  - installation.md
  - packaging.md
  - cli.md
  - api.md
  - tests.md
