/*
 * config.h - generated by CMake (configure_file).
 *
 * This mirrors the subset of the autotools config.h that the Elektroid
 * sources actually consume. The autotools build (config.h generated by
 * autoheader/configure) remains the reference; this file only needs to
 * provide the same macros for a CMake build.
 */

#ifndef ELEKTROID_CONFIG_H
#define ELEKTROID_CONFIG_H

/* Package identification (autoconf AC_INIT). */
#define PACKAGE "@PACKAGE@"
#define PACKAGE_NAME "@PACKAGE_NAME@"
#define PACKAGE_TARNAME "@PACKAGE_TARNAME@"
#define PACKAGE_VERSION "@PACKAGE_VERSION@"
#define PACKAGE_STRING "@PACKAGE_STRING@"
#define PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"
#define PACKAGE_URL "@PACKAGE_URL@"
#define VERSION "@VERSION@"

/* Set to 1 if libsndfile >= 1.1.0 (MP3 read/write support). */
#define HAVE_SNDFILE_MP3 @HAVE_SNDFILE_MP3@

/* Backend selection. Defined only when the RtMidi / RtAudio backends are
 * used; the ALSA / PulseAudio backends are selected by their absence, so
 * the source guards (#if defined(ELEKTROID_RTMIDI) ...) keep working. */
#cmakedefine ELEKTROID_RTMIDI 1
#cmakedefine ELEKTROID_RTAUDIO 1

/* Header availability (autoconf AC_CHECK_HEADERS). */
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_LIMITS_H 1

#endif /* ELEKTROID_CONFIG_H */
